In [6]:
import numpy as np

arreglo = np.arange(1, 26).reshape(5, 5)
matriz_central = arreglo[1:4, 1:4]

print(arreglo)
print(matriz_central)





[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9]
 [12 13 14]
 [17 18 19]]
